# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Publish Broker + Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
          - os: ubuntu-latest
            runtime: linux-x64

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # 3. Restore
      - name: Restore
        run: dotnet restore onishiro.logspy.sln

      # 4. Build
      - name: Build
        run: dotnet build onishiro.logspy.sln --no-restore --configuration Release

      # 5. Publish Broker
      - name: Publish Broker
        run: |
          dotnet publish src/onishiro.logspy.broker/onishiro.logspy.broker.csproj --configuration Release --runtime ${{ matrix.runtime }} --self-contained true /p:PublishTrimmed=false -o artifacts/broker-${{ matrix.runtime }}
        shell: bash
        if: runner.os != 'Windows'

      - name: Publish Broker (Windows)
        run: >
          dotnet publish src/onishiro.logspy.broker/onishiro.logspy.broker.csproj
          --configuration Release
          --runtime ${{ matrix.runtime }}
          --self-contained true
          /p:PublishTrimmed=false
          -o artifacts/broker-${{ matrix.runtime }}
        if: runner.os == 'Windows'

      # 6. Publish Client
      - name: Publish Client
        run: |
          dotnet publish src/onishiro.logspy.client/onishiro.logspy.client.csproj --configuration Release --runtime ${{ matrix.runtime }} --self-contained true /p:PublishTrimmed=false -o artifacts/client-${{ matrix.runtime }}
        shell: bash
        if: runner.os != 'Windows'

      - name: Publish Client (Windows)
        run: >
          dotnet publish src/onishiro.logspy.client/onishiro.logspy.client.csproj
          --configuration Release
          --runtime ${{ matrix.runtime }}
          --self-contained true
          /p:PublishTrimmed=false
          -o artifacts/client-${{ matrix.runtime }}
        if: runner.os == 'Windows'

      # 7. Upload Broker Artifact
      - name: Upload Broker Artifact
        uses: actions/upload-artifact@v4
        with:
          name: broker-${{ matrix.runtime }}
          path: artifacts/broker-${{ matrix.runtime }}

      # 8. Upload Client Artifact
      - name: Upload Client Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-${{ matrix.runtime }}
          path: artifacts/client-${{ matrix.runtime }}

