# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout source code
      - uses: actions/checkout@v4

      # 2. Setup .NET SDK
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # 3. Restore dependencies for the solution
      - name: Restore dependencies
        run: dotnet restore onishiro.logspy.sln

      # 4. Build all projects in the solution
      - name: Build solution
        run: dotnet build onishiro.logspy.sln --no-restore --configuration Release

      # 5. Run tests (only if test projects exist)
      - name: Run tests
        run: dotnet test onishiro.logspy.sln --no-build --verbosity normal || echo "No tests found, skipping."
